#!/bin/bash

if ! which newsboat 2>/dev/null 1>&2; then
    echo "No RSS"
    exit 0
fi

if [ ! -f "$HOME/.newsboat/urls" ]; then
    echo "No URLs"
    exit 0
fi

case $BLOCK_BUTTON in
    1) $TERMINAL -e newsboat ;;
esac

echo  $(newsboat -x print-unread | cut -d' ' -f1)
