#!/bin/bash

case $BLOCK_BUTTON in
    1) st -e ncpamixer & disown ;;
    3) pamixer -t ;;
    4) pamixer -i 5 ;;
    5) pamixer -d 5 ;;
esac

printpastatus() {
    [[ $(pamixer --get-mute) = "true" ]] && echo -n 🔇 mute && exit

    LEVEL=$(pamixer --get-volume)
    if [ $LEVEL -eq 0 ]; then
        echo "🔇 $LEVEL%"
    elif [ $LEVEL -lt 30 ]; then
        echo "🔈 $LEVEL%"
    elif [ $LEVEL -lt 70 ]; then
        echo "🔉 $LEVEL%"
    elif [ $LEVEL -lt 100 ]; then
        echo "🔊 $LEVEL%"
    else
        echo "🔊$LEVEL%"
    fi
}
printpastatus
