#!/bin/bash
export MPD_HOST=$HOME/.mpd/socket

newvol="pkill -RTMIN+10 i3blocks"
newmpd="pkill -RTMIN+12 i3blocks"

case "$1" in
    "up") pamixer -i "$2" ; $newvol ;;
    "down") pamixer -d "$2" ; $newvol ;;
    "mute") pamixer -t ; $newvol ;;
    "truemute") pamixer -m ; $newvol ;;
    "toggle") mpc toggle ; $newmpd ;;
    "pause") mpc pause ; $newmpd ;;
    "forward") mpc seek +"$2" ; $newmpd ;;
    "back") mpc seek -"$2" ; $newmpd ;;
    "next") mpc next ; $newmpd ;;
    "prev") mpc prev ; $newmpd ;;
    "stop") mpc stop ; $newmpd ;;
    "replay") mpc seek 0% ; $newmpd ;;
esac
