#!/bin/sh -e

# Take a screenshot
scrot /tmp/screen_locked.png

# Pixelate
convert /tmp/screen_locked.png -scale 5% -scale 2000% /tmp/screen_locked2.png

# Delete raw screenshot
rm /tmp/screen_locked.png

# Lock the screen
i3lock -i /tmp/screen_locked2.png
