#!/bin/bash

PROJECT_NAME="$1"
GIT_URL="$2"

CODE_DIR="$HOME/code"

if [[ -z $PROJECT_NAME ]]; then
    echo "What should I name the project?"
    exit 1
fi

find_next_code() {
    local CODE
    CODE=$(find $CODE_DIR -maxdepth 1 -type d -printf "%f\n" | grep -P '\d{3}\-' | sort | tail -n1 | cut -d'-' -f1)
    format_code $(($CODE + 1))
}

format_code() {
    if [[ $1 -lt 10 ]]; then
        echo "00$1"
    elif [[ $1 -lt 100 ]]; then
        echo "0$1"
    else
        echo $1
    fi
}

NEXT_CODE=$(find_next_code)
NEW_DIR="$CODE_DIR/$NEXT_CODE-$PROJECT_NAME"

if [[ -n $GIT_URL ]]; then
    git clone "$GIT_URL" "$NEW_DIR"
else
    mkdir "$NEW_DIR"
    cd "$NEW_DIR"
    git init
    echo 'private/' > .gitignore
    mkdir private
fi

echo "Project Code: $NEXT_CODE"
