#!/bin/bash

toggle_mute() {
    if pamixer --get-mute; then
        pamixer -u
    else
        pamixer -m
    fi
}

case $1 in
    up) pamixer -i 5 ;;
    down) pamixer -d 5 ;;
    mute) toggle_mute ;;
esac

# Notify i3blocks of volume change
pkill -RTMIN+10 i3blocks
