[terminal.shell]
program = "/usr/local/bin/fish"
args = [
  "-c",
  "tmux attach\\; choose-tree -Zs || tmux new -t default && exit"
]

[window]
opacity = 0.9
padding = { x = 20, y = 20 }

[font]
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }
size = 16

[terminal]
