vim.keymap.set('n', '<leader>K', 'ji')
vim.keymap.set('n', '<leader>J', 'J^')
vim.keymap.set('n', '<leader>pv', vim.cmd.Ex)
vim.keymap.set('n', '<leader>H', ':Hardtime toggle<cr>')
vim.keymap.set('n', '<leader>b', ':buffers<CR>:buffer<Space>')
vim.keymap.set('n', '<leader>i', ':setlocal list!<cr>')
vim.keymap.set('n', '<leader>l', ':source ~/.config/nvim/init.lua<cr>')
vim.keymap.set('n', '[e', ':m -2<CR>')
vim.keymap.set('n', ']e', ':m +1<CR>')
vim.keymap.set('n', '<leader>n', ':NERDTreeToggle<CR>')
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist)
vim.keymap.set({ 'n', 'v' }, '<leader>y', [["+y]])
vim.keymap.set('n', '<leader>Y', [["+Y]])
vim.keymap.set('n', '<leader>o', 'o<ESC>')
vim.keymap.set('n', '<leader>O', 'O<ESC>')
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', '<C-u>', '<C-u>zz')
vim.keymap.set('n', '<C-f>', '<C-f>zz')
vim.keymap.set('n', '<C-b>', '<C-b>zz')
vim.keymap.set('n', '<leader><leader>', ',')
vim.keymap.set('v', '<leader>p', [["_dP]])
vim.keymap.set('n', '<leader>x', "<cmd>!chmod +x %<CR>", { silent = true })

-- Easier window navigation
vim.keymap.set('n', "<C-Right>", "<C-w>l")
vim.keymap.set('n', "<C-Left>", "<C-w>h")
vim.keymap.set('n', "<C-Down>", "<C-w>j")
vim.keymap.set('n', "<C-Up>", "<C-w>k")
