#!/bin/sh -e

# Don't lock twice
[ pgrep i3lock ] && exit

if [ -f "$HOME/Pictures/lock_screen.png" ]; then
    i3lock -e -i $HOME/Pictures/lock_screen.png
    exit
fi

# Take a screenshot
scrot /tmp/screen_locked.png

# Pixelate
convert /tmp/screen_locked.png -scale 5% -scale 2000% /tmp/screen_locked2.png

# Delete raw screenshot
rm /tmp/screen_locked.png

# Lock the screen
i3lock -e -i /tmp/screen_locked2.png
