#!/usr/bin/env bash

# Switch back and forth between files to alleviate any inode issues
PAPER1='/tmp/wallpaper-1.png'
PAPER2='/tmp/wallpaper-2.png'
FALLBACK="$HOME/Pictures/wallpaper.png"
OVERLAY_IMG="$HOME/Pictures/wallpaper_overlay.png"
OVERLAY_IMG_NE="$HOME/Pictures/wallpaper_overlay_ne.png"
OVERLAY_IMG_NW="$HOME/Pictures/wallpaper_overlay_nw.png"
OVERLAY_IMG_SE="$HOME/Pictures/wallpaper_overlay_se.png"
OVERLAY_IMG_SW="$HOME/Pictures/wallpaper_overlay_sw.png"
LOCK_SCREEN="$HOME/Pictures/lock_screen.png"

if [[ -f $OVERLAY_IMG ]]; then
    OVERLAY_IMG_NE="$OVERLAY_IMG"
fi

getFileSize() {
    stat --printf="%s" "$1"
}

isPortrait() {
    [ ! -f "$1" ] && return 0
    width=$(file "$1" | cut -d',' -f2 | tr -d ' ' | cut -d'x' -f1)
    height=$(file "$1" | cut -d',' -f2 | tr -d ' ' | cut -d'x' -f2)
    [ "$height" -gt "$width" ]
}

getGeo() {
    if isPortrait "$1"; then
        echo '500x700+0+0'
    else
        echo '700x500+0+0'
    fi
}

overlayImg() {
    if [[ -f "$2" ]]; then
        composite -gravity $1 -geometry "$(getGeo $2)" "$2" "$CURRENT_PAPER" "$CURRENT_PAPER"
    fi
}

CURRENT_PAPER=''

if [[ -f $PAPER1 ]]; then
    CURRENT_PAPER=$PAPER2
else
    CURRENT_PAPER=$PAPER1
fi

TRIES=0
while [ $TRIES -lt 5 ]; do
    curl -sSL "https://picsum.photos/3840/2160/?random" > "$CURRENT_PAPER"
    if [[ $? -eq 0 ]]; then
        break
    fi

    TRIES=$((TRIES+1))
    sleep 5
done

if [[ $TRIES -eq 5 ]]; then
    CURRENT_PAPER=$FALLBACK
fi

if [[ $(getFileSize "$CURRENT_PAPER") -eq 0 ]]; then
    CURRENT_PAPER=$FALLBACK
fi

overlayImg NorthEast "$OVERLAY_IMG_NE"
overlayImg NorthWest "$OVERLAY_IMG_NW"
overlayImg SouthEast "$OVERLAY_IMG_SE"
overlayImg SouthWest "$OVERLAY_IMG_SW"

dconf write /com/deepin/wrap/gnome/desktop/background/picture-uri "'$CURRENT_PAPER'"
dconf write /org/cinnamon/desktop/background/picture-uri "'file://$CURRENT_PAPER'"
dconf write /org/cinnamon/desktop/background/picture-options "'stretched'"
feh --bg-scale $CURRENT_PAPER

# Generate lock screen image
magick $CURRENT_PAPER $CURRENT_PAPER \
    +append \
    -resize $(xdpyinfo | awk '/dimensions/{print $2}')\! \
    $LOCK_SCREEN

if [[ $CURRENT_PAPER == $FALLBACK ]]; then
    exit
fi

if [[ $CURRENT_PAPER == $PAPER1 ]]; then
    rm -rf $PAPER2
else
    rm -rf $PAPER1
fi
