#!/usr/bin/env bash

# Switch back and forth between files to alleviate any inode issues
PAPER1='/tmp/wallpaper-1.png'
PAPER2='/tmp/wallpaper-2.png'
FALLBACK="$HOME/Pictures/wallpaper.png"
LOCK_SCREEN="$HOME/Pictures/lock_screen.png"

CURRENT_PAPER=''

if [[ -f $PAPER1 ]]; then
    CURRENT_PAPER=$PAPER2
else
    CURRENT_PAPER=$PAPER1
fi

curl -sSL "https://picsum.photos/3840/2160/?random" > "$CURRENT_PAPER"
if [[ $? -ne 0 ]]; then
    CURRENT_PAPER=$FALLBACK
fi

getFileSize() {
    du --apparent-size --block-size=1 "$1" | awk '{print $1}'
}

if [[ $(getFileSize "$CURRENT_PAPER") -eq 0 ]]; then
    CURRENT_PAPER=$FALLBACK
fi


dconf write /com/deepin/wrap/gnome/desktop/background/picture-uri "'$CURRENT_PAPER'"
dconf write /org/cinnamon/desktop/background/picture-uri "'file://$CURRENT_PAPER'"
dconf write /org/cinnamon/desktop/background/picture-options "'stretched'"
feh --bg-scale $CURRENT_PAPER

# Generate lock screen image
convert $CURRENT_PAPER $CURRENT_PAPER \
    +append \
    -resize $(xdpyinfo | awk '/dimensions/{print $2}')\! \
    $LOCK_SCREEN

if [[ $CURRENT_PAPER == $FALLBACK ]]; then
    exit
fi

if [[ $CURRENT_PAPER == $PAPER1 ]]; then
    rm -rf $PAPER2
else
    rm -rf $PAPER1
fi
