#!/usr/bin/env bash

# Switch back and forth between files to alleviate any inode issues
PAPER1='/tmp/wallpaper-1.png'
PAPER2='/tmp/wallpaper-2.png'

CURRENT_PAPER=''

if [[ -f $PAPER1 ]]; then
    CURRENT_PAPER=$PAPER2
else
    CURRENT_PAPER=$PAPER1
fi

curl -sSL "https://unsplash.it/3840/2160/?random" > "$CURRENT_PAPER"

dconf write /com/deepin/wrap/gnome/desktop/background/picture-uri "'$CURRENT_PAPER'"
# dconf write /org/cinnamon/desktop/background/picture-uri "'file://$CURRENT_PAPER'"
feh --bg-scale $CURRENT_PAPER # Cinnamon works with feh, deepin doesn't

if [[ $CURRENT_PAPER == $PAPER1 ]]; then
    rm -rf $PAPER2
else
    rm -rf $PAPER1
fi
