#! /bin/bash

SXHKD_SHELL=bash sxhkd &

# Startup applications
# Enable NumLock
numlockx &
# Start dunst for notifications:
dunst &
# Music player daemon:
pgrep -x mpd || mpd &
# Run the script to update the mpd i3block on change.
pgrep -x i3mpdupdate || i3mpdupdate &
# Autolock desktop after 5 minutes
xautolock -time 5 -locker lock_screen -corners ---- &
# Turn off displays after 5 minutes
xset dpms 300 300 300 &
# Set wallpaper
feh --bg-scale $HOME/Pictures/wallpaper.jpg &
# Set screen layout
$HOME/.screenlayout/default.sh &
# Start compositor
compton -f &
# Start Network Manager
nm-applet &
# Unclutter makes the mouse invisible after a brief period
unclutter -notclass 'Google-chrome' 'Code' 'Firefox' 'VSCodium' &
# Runs the key remapping scripts
$HOME/.scripts/remaps &
# Automounter
pgrep -x udiskie || udiskie --tray &
# Fix scroll issue in VSCode
imwheel --kill --buttons "45"

$HOME/.config/polybar/launch.sh

# Clear existing rules
bspc rule -r "*"

# aliases for common desktops
BSPWM_WINDOW_WEB=$BSPWM_WINDOW_1
BSPWM_WINDOW_TERMINAL=$BSPWM_WINDOW_2
BSPWM_WINDOW_EMAIL=$BSPWM_WINDOW_3
BSPWM_WINDOW_EDITOR=$BSPWM_WINDOW_4

monitors=( $(bspc query --monitors --names) )

if [ ${#monitors[*]} -eq 1 ]; then
    bspc monitor -d $BSPWM_WINDOW_WEB \
        $BSPWM_WINDOW_TERMINAL \
        $BSPWM_WINDOW_EMAIL \
        $BSPWM_WINDOW_EDITOR \
        $BSPWM_WINDOW_5 \
        $BSPWM_WINDOW_6 \
        $BSPWM_WINDOW_7 \
        $BSPWM_WINDOW_8 \
        $BSPWM_WINDOW_9 \
        $BSPWM_WINDOW_10
elif [ ${#monitors[*]} -eq 2 ]; then
    bspc monitor ${monitors[0]} -d $BSPWM_WINDOW_WEB $BSPWM_WINDOW_EDITOR \
        $BSPWM_WINDOW_5 $BSPWM_WINDOW_6 $BSPWM_WINDOW_7
    bspc monitor ${monitors[1]} -d $BSPWM_WINDOW_EMAIL $BSPWM_WINDOW_TERMINAL \
        $BSPWM_WINDOW_8 $BSPWM_WINDOW_9 $BSPWM_WINDOW_10
else
    bspc monitor ${monitors[0]} -d $BSPWM_WINDOW_WEB $BSPWM_WINDOW_5 $BSPWM_WINDOW_6
    bspc monitor ${monitors[1]} -d $BSPWM_WINDOW_TERMINAL $BSPWM_WINDOW_EDITOR $BSPWM_WINDOW_7 $BSPWM_WINDOW_8
    bspc monitor ${monitors[2]} -d $BSPWM_WINDOW_EMAIL $BSPWM_WINDOW_9 $BSPWM_WINDOW_10
fi

bspc desktop -f $BSPWM_WINDOW_WEB

bspc config border_width         3
bspc config window_gap          10
bspc config top_padding         24

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# desktop specific settings
bspc desktop $BSPWM_WINDOW_WEB --layout monocle
bspc config -d $BSPWM_WINDOW_WEB border_width 0
bspc config -d $BSPWM_WINDOW_WEB window_gap 0
bspc config -d $BSPWM_WINDOW_WEB top_padding 0

bspc rule -a Code desktop=$BSPWM_WINDOW_EDITOR
bspc rule -a firefox desktop=$BSPWM_WINDOW_WEB
bspc rule -a Gimp desktop=$BSPWM_WINDOW_5 state=floating follow=on
bspc rule -a Gnome-terminal desktop=$BSPWM_WINDOW_TERMINAL
bspc rule -a Google-chrome desktop=$BSPWM_WINDOW_WEB
bspc rule -a Hexchat desktop=$BSPWM_WINDOW_EDITOR
bspc rule -a Mattermost desktop=$BSPWM_WINDOW_EMAIL
bspc rule -a st-terminal desktop=$BSPWM_WINDOW_TERMINAL
bspc rule -a Thunar state=floating
bspc rule -a Thunderbird desktop=$BSPWM_WINDOW_EMAIL
bspc rule -a VSCodium desktop=$BSPWM_WINDOW_EDITOR
bspc rule -a "VirtualBox Manager" desktop=$BSPWM_WINDOW_6

# Terminal scratchpad
bspc rule -a scratchpad hidden=on sticky=on state=floating
[ ! -f /tmp/scratchid ] && st -c scratchpad -e bspwm-scratchpad &

# Any popup type terminal windows
bspc rule -a "*:popup_window" state=floating rectangle=825x500 center

# Any popup type terminal windows large
bspc rule -a "*:popup_window_large" state=floating rectangle=1500x750 center
